[rime-ice]
src.git = "https://github.com/iDvel/rime-ice"
fetch.github = "iDvel/rime-ice"

[yazi-plugins]
src.git = "https://github.com/yazi-rs/plugins"
fetch.github = "yazi-rs/plugins"

[yazi-bookmarks]
src.git = "https://github.com/dedukun/bookmarks.yazi"
fetch.github = "dedukun/bookmarks.yazi"

[vesktop-theme-system24]
src.git = "https://github.com/refact0r/system24.git"
fetch.github = "refact0r/system24"
