# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rime-ice = {
    pname = "rime-ice";
    version = "07d0e1cc67f1bbb46672c5c4c751858f34a83780";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "07d0e1cc67f1bbb46672c5c4c751858f34a83780";
      fetchSubmodules = false;
      sha256 = "sha256-AoQUH2zWf4/BWxxO9+kir+f33TpA80bo3Ur4+/f+FdI=";
    };
    date = "2025-11-17";
  };
  vesktop-theme-system24 = {
    pname = "vesktop-theme-system24";
    version = "92e08baf66b54f590b5ab9109b4b7399889ac05d";
    src = fetchFromGitHub {
      owner = "refact0r";
      repo = "system24";
      rev = "92e08baf66b54f590b5ab9109b4b7399889ac05d";
      fetchSubmodules = false;
      sha256 = "sha256-+MekQmf9ruSlFfCJ9R8RGq/Bl0Olhmst+YpjKS0kH9M=";
    };
    date = "2025-11-16";
  };
  yazi-bookmarks = {
    pname = "yazi-bookmarks";
    version = "9ef1254d8afe88aba21cd56a186f4485dd532ab8";
    src = fetchFromGitHub {
      owner = "dedukun";
      repo = "bookmarks.yazi";
      rev = "9ef1254d8afe88aba21cd56a186f4485dd532ab8";
      fetchSubmodules = false;
      sha256 = "sha256-GQFBRB2aQqmmuKZ0BpcCAC4r0JFKqIANZNhUC98SlwY=";
    };
    date = "2025-07-09";
  };
  yazi-compress = {
    pname = "yazi-compress";
    version = "c2646395394f22b6c40bff64dc4c8c922d210570";
    src = fetchFromGitHub {
      owner = "KKV9";
      repo = "compress.yazi";
      rev = "c2646395394f22b6c40bff64dc4c8c922d210570";
      fetchSubmodules = false;
      sha256 = "sha256-qAuMD4YojLfVaywurk5uHLywRRF77U2F7ql+gR8B/lo=";
    };
    date = "2025-08-15";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "2301ff803a033cd16d16e62697474d6cb9a94711";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "2301ff803a033cd16d16e62697474d6cb9a94711";
      fetchSubmodules = false;
      sha256 = "sha256-+lirIBXv3EvztE/1b3zHnQ9r5N3VWBCUuH3gZR52fE0=";
    };
    date = "2025-11-19";
  };
}
