# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  rime-ice = {
    pname = "rime-ice";
    version = "c7fdbb25d6b2e50f65dfae7923a74b5272e934c2";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "c7fdbb25d6b2e50f65dfae7923a74b5272e934c2";
      fetchSubmodules = false;
      sha256 = "sha256-ayXzpWrRq6a0g69Ohx+tHbo3YfjERhdEsCK1IMoTypw=";
    };
    date = "2025-12-03";
  };
  vesktop-theme-system24 = {
    pname = "vesktop-theme-system24";
    version = "92e08baf66b54f590b5ab9109b4b7399889ac05d";
    src = fetchFromGitHub {
      owner = "refact0r";
      repo = "system24";
      rev = "92e08baf66b54f590b5ab9109b4b7399889ac05d";
      fetchSubmodules = false;
      sha256 = "sha256-+MekQmf9ruSlFfCJ9R8RGq/Bl0Olhmst+YpjKS0kH9M=";
    };
    date = "2025-11-16";
  };
  yazi-bookmarks = {
    pname = "yazi-bookmarks";
    version = "9ef1254d8afe88aba21cd56a186f4485dd532ab8";
    src = fetchFromGitHub {
      owner = "dedukun";
      repo = "bookmarks.yazi";
      rev = "9ef1254d8afe88aba21cd56a186f4485dd532ab8";
      fetchSubmodules = false;
      sha256 = "sha256-GQFBRB2aQqmmuKZ0BpcCAC4r0JFKqIANZNhUC98SlwY=";
    };
    date = "2025-07-09";
  };
  yazi-compress = {
    pname = "yazi-compress";
    version = "c2646395394f22b6c40bff64dc4c8c922d210570";
    src = fetchFromGitHub {
      owner = "KKV9";
      repo = "compress.yazi";
      rev = "c2646395394f22b6c40bff64dc4c8c922d210570";
      fetchSubmodules = false;
      sha256 = "sha256-qAuMD4YojLfVaywurk5uHLywRRF77U2F7ql+gR8B/lo=";
    };
    date = "2025-08-15";
  };
  yazi-plugins = {
    pname = "yazi-plugins";
    version = "eaf6920b7439fa7164a1c162a249c3c76dc0acd9";
    src = fetchFromGitHub {
      owner = "yazi-rs";
      repo = "plugins";
      rev = "eaf6920b7439fa7164a1c162a249c3c76dc0acd9";
      fetchSubmodules = false;
      sha256 = "sha256-B6zhZfp3SEaiviIzosI2aD8fk+hQF0epOTKi1qm8V3E=";
    };
    date = "2025-11-25";
  };
}
