"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
  { on = [
    "<C-s>",
  ], run = '''shell "$SHELL" --block --confirm''', desc = "Open shell here" },
  { on = [ "<C-n>" ], run = '''
    shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
  ''' },
  { on = [
    "c",
    "a",
  ], run = "plugin compress", desc = "Archive selected files" },
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "chmod on slected files" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = "K", run = "arrow -50%", desc = "Move cursor up half page" },
  { on = "J", run = "arrow 50%", desc = "Move cursor down half page" },
  { on = "<A-k>", run = "arrow -5", desc = "Move cursor up half page" },
  { on = "<A-j>", run = "arrow 5", desc = "Move cursor down half page" },
  { on = [
    "f",
    "f",
  ], run = "filter --smart", desc = "Filter files" },
  { on = [
    "f",
    "c",
  ], run = "plugin jump-to-char", desc = "Jump to char" },
  { on = [
    "f",
    "F",
  ], run = "plugin smart-filter", desc = "Smart Filter" },
  { on = "S", run = "search fd", desc = "Search files by name using fd" },
  { on = [
    "T",
    "h",
  ], run = "plugin --sync hide-preview", desc = "Hide or show the preview" },
  { on = [
    "T",
    "m",
  ], run = "plugin --sync max-preview", desc = "Max or restore the preview" },
  { on = [
    "y",
  ], run = [
    '''shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm''',
    "yank",
  ], desc = "yank files and copy to clipboard" },
  { on = [
    "l",
  ], run =  "plugin --sync smart-enter",desc = "Enter the child directory, or open the file" },
  { on = [
    "<Right>",
  ], run =  "plugin --sync smart-enter",desc = "Enter the child directory, or open the file" },
  { on = [
    "p",
  ], run =  "plugin --sync smart-paste",desc = "paste into the hovered dir or CWD" },
  { on = [
    "m",
  ], run =  "plugin bookmarks --args=save",desc = "Save current position as a bookmark" },
  { on = [
    "'",
  ], run =  "plugin bookmarks --args=jump",desc = "Jump to a bookmark" },
  { on = [
    "b",
    "d",
  ], run =  "plugin bookmarks --args=delete",desc = "delete a bookmark" },
  { on = [
    "b",
    "D",
  ], run =  "plugin bookmarks --args=delete_all",desc = "delete all bookmark" },
  { on = "M", run = "create --dir", desc = "Create a dir" },
]

append_keymap = [
  { on = [
    "e",
  ], run = "open", desc = "Open the selected files" },
  { on = [
    "E",
  ], run = "open --interactive", desc = "Open the selected files interactively" },
  { on = [
    "g",
    "n",
  ], run = "cd /nix/etc", desc = "Go to the nix dir" },
  { on = [
    "g",
    "V",
  ], run = "cd ~/Videos/", desc = "Go to the videos directory" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/VI/", desc = "Go to the VI directory" },
  { on = [
    "g",
    "p",
  ], run = "cd ~/Pictures/", desc = "Go to the pictures directory" },
  { on = [
    "g",
    "s",
  ], run = "cd ~/Pictures/Screenshots/", desc = "Go to the screenshots directory" },
  { on = [
    "g",
    "d",
  ], run = "cd ~/Downloads/", desc = "Go to the downloads directory" },
  { on = [
    "g",
    "D",
  ], run = "cd ~/Desktop/", desc = "Go to the desktop directory" },
  { on = [
    "g",
    "m",
  ], run = "cd /run/media/$USER", desc = "Go to the media directory" },
  { on = [
    "g",
    "l",
  ], run = "cd ~/.local", desc = "Go to the local directory" },
  { on = [
    "g",
    "t",
  ], run = "cd ~/.local/share/Trash/files", desc = "Go to the trash directory" },
]

[input]

prepend_keymap = [{ on = ["<Esc>"], run = "close", desc = "Cancel input" }]

[completion]
prepend_keymap = [
  { on = "<C-k>", run = "arrow -1", desc = "Move cursor up" },
  { on = "<C-j>", run = "arrow 1", desc = "Move cursor down" },
]
